### ISSUE TITLE
What is the default login?

### ISSUE THREAD

**Issue by adriadam10** [hxcan/ftpserver#1]
I'm running the server perfectly, but i don't know what is the default login.
Another question, is if there is some function to change the user and the password for the login.
Good night.

**Comment by hxcan** [comment]
Hello.

**There is no access control yet.
Any user name and password will be accepted.**

I wrote the ftpserver lib from scratch. It is only used in my own applications.
 Didn't expect to have real person interested so quickly yet, ;-)  .

Please be noticed that I have only tested it with the builtin ftp client of kde5 dolphin file manager.

**Comment by hxcan** [comment]
@adriadam10 
Setting the user name and password is supported now. 

This is an example of setting user name and password:
https://github.com/hxcan/hxftpserver/blob/master/app/src/main/java/com/stupidbeauty/builtinftp/BuiltinFtpServer.java#L124

Also, it is fully functional with filezilla client now:

1. listing
2. downloading
3. uploading
