### ISSUE TITLE
Android 11+

### ISSUE THREAD

**Issue by eakteam** [hxcan/ftpserver#10]
Will you implement DocumentFile and scoped storage except old File way?

**Comment by hxcan** [comment]
OK.
It is also on my wish list.

**Comment by eakteam** [comment]
> OK. It is also on my wish list.

Do you have any ETA on this? The app is not working on Android 11+...

**Comment by hxcan** [comment]
I have changed the target api level to 30(Android 11) in the hxftpserver application and the ftpserver library. The existing code is working as expected on my testing device, which is running Android 12. You can try the most recent commit of hxftpserver application: https://github.com/hxcan/hxftpserver/tree/a405014731a55d8324ec49acce08d4304731444b

And I'm doing some research and going to abstract the logic based on the DocumentFile API instead of the File API, to better support one of my own use-cases. What is your actual problem about this issue? 
What do you mean by this ?

> The app is not working on Android 11+...

Please give me some more details about your use-case, and some screen shots / screen records.

**Comment by hxcan** [comment]
As I do not know the details of your problem, I have to do it according to my own plan. And now my own requirement has been fulfilled.

There are two changes which might help solve your problem, whatever it is:
1. The ftpserver library will notify the calling application of an event "NEED_EXTERNAL_STORAGE_MANAGER_PERMISSION", when it needs the permission of "Managing all files" to do its job. By default, the ftpserver library does its work based on the File api, which is more effecient than the Storage Access Framework. And it needs this permission to work properly on Android 11 and higher versions. https://github.com/hxcan/ftpserver/commit/6d3f82f0279a98b0c474c55db69a5e97889a9372#diff-3d69424eee52bf60d527f532cded020ca311e57fc0322a97ad52a2ab74af6df5R11 . The application is supposed to show some kind of prompt and guide the user to the system settings page of granting "Managing all files" permission. This is demonstrated by the hxftpserver application: https://github.com/hxcan/hxftpserver/commit/de4f5291180f1ab6f1ed49d353c45d0567cce3f7#diff-34b9d8d14418eddcfcd2764fa5f116c9dbe40881e1d755a489a3961d14a49f35R41
2. The ftpserver library provides an api of mounting a Uri to a virtual path.  https://github.com/hxcan/ftpserver/commit/5484b8b3232cdf3f50d97093f83d8f213d049774#diff-b35f6a0ef28c102a1e8f3eeff2f397bac3c151480e67b4ec775f07c5877a4101R320  The application can guide the user to select a directory on the external storage with the help of the Storage Access Framework, and then mount that returned Uri to a virtual path of the ftpserver. With this api, the calling application can even overwrite the root directory of the ftpserver. This is compatible with the Scoped Storage model provided by Android, although it's a little slower than the raw File mode. It is demonstrated by the hxftpserver application: https://github.com/hxcan/hxftpserver/commit/de4f5291180f1ab6f1ed49d353c45d0567cce3f7#diff-3841e77b4c74774f7ccc9816bece53cc041cf08f1f50e5fbc7682b554ce143a1R105

You can try these features with the latest precomiled version of hxftpserver:
https://stupidbeauty.com/ArticleImages/1907/HxFtpServer.4623.2023.4.4.e.apk

I'm going to merge this branch and close this issue.
Please open it again and provide some details about your problem if your it was still not solved.
