### ISSUE TITLE
can't compile in android studio

### ISSUE THREAD

**Issue by francoisnicolas** [hxcan/ftpserver#12]
Something is missing in the project : 
there is a 'add configuration' message

**Comment by hxcan** [comment]
I have not used Android Studio for a long time. I'll try it myself.

Please:
1. provide some screen shots and logs of android studio.
2. Try these 'gradlew' commands directly in an console in the root directory of the project:
    ./gradlew assembleDebug
    ./gradlew installDebug

**Comment by hxcan** [comment]
I have tried with the latest version of Android Studio:
Android Studio Flamingo | 2022.2.1 Patch 2

It works as expected.

Please provide some logs and screen shots about your current problem, and try to compile it with the latest version of Android Studio.

**Comment by francoisnicolas** [comment]
here is a log (under WINDOWS/MS-DOS)
PS G:\ftpserver-master> ./gradlew assembleDebug
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'G:\ftpserver-master\settings.gradle' (C:\Users\auror\.gradle\caches\7.5\scripts\916uvh0t6tz3gyl3omv1c3lxt).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

It's not the latest Android Studio (Electric EEl 2022), and perhaps I haven't added all the settings for compiling in command line, as I always use Android Studio with the graphical interface.

**Comment by hxcan** [comment]
It looks like that you are using a JDK version too high for the version of gradle we are using. jdk 19?
Please help me confirm it with these settings:
https://stackoverflow.com/a/75114912

Try to set it to openjdk 11 and check if it solved the problem.

And please tell me the jdk version you are using.

**Comment by francoisnicolas** [comment]
Now, it compiles
You should add these explanations (change jdk) in the README file, and perhaps update your github project with this value of jdk
and explain how to compile from command line
Thank you

**Comment by hxcan** [comment]
OK. I'll add some instructions about the jdk verison in the readme. And add the support of newer version of the jdk.

**Comment by francoisnicolas** [comment]
I have just installed your app that use this library. It works fine.
Have you got a link to a github android project for a ftp client ?

**Comment by hxcan** [comment]
No, I do not know of any android ftp clients.
I use the clients on computer usually.

**Comment by hxcan** [comment]
Now we support openjdk11 to openjdk19
