### ISSUE TITLE
How to stop the FTP server?

### ISSUE THREAD

**Issue by fiasko131** [hxcan/ftpserver#14]
I was able to successfully implement your library in my app, but one essential thing is missing for me: How to stop the server?
Do you have an idea?
Thank you for this good work.

**Comment by hxcan** [comment]
This feature is not implemented yet.

**Comment by hxcan** [comment]
The feature is implemented now.

You can stop the FTP server at runtime like this:
https://github.com/hxcan/hxftpserver/commit/9986d76048041ff8ea8c15acddc28bec95350396#diff-b9a19f3b2f9a51896a8fe8a0ca05b1723c5557557a68123cf8cdd81458256889R125

```
    ftpServer.stop();
```

You have to use the latest version "2023.10.24".

**Comment by hxcan** [comment]
The feature is implemented now.

You can stop the FTP server at runtime like this:
https://github.com/hxcan/hxftpserver/commit/9986d76048041ff8ea8c15acddc28bec95350396#diff-b9a19f3b2f9a51896a8fe8a0ca05b1723c5557557a68123cf8cdd81458256889R125

```
    ftpServer.stop();
```

You have to use the latest version "2023.10.24".

**Comment by fiasko131** [comment]
Thanks, I achieved the same result with a similar method.
